# Generated by Django 3.1.7 on 2021-04-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemcategory',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='itemtype',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
