# Generated by Django 3.1.7 on 2021-04-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210427_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='fbdesc',
            new_name='Desc',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='fbemail',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='fbimg',
            new_name='Img',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='fbname',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='fbtime',
            new_name='Time',
        ),
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.FileField(upload_to='pics'),
        ),
    ]
